# **Chiziqli algebra masalalarini ishlash: Linear algebra moduli**#

In [1]:
from numpy import linalg
import numpy as np

array1 = np.array([3, 4, 6, 8, 9])
array2 = np.array([0, 1, -1, 2, 3])

Matritsalarni qo'shish

In [2]:
array1 + array2

array([ 3,  5,  5, 10, 12])

Matritsalarni ayirish

In [3]:
array1 - array2

array([3, 3, 7, 6, 6])

Matritsalarni ko'paytirish

In [36]:
#array1 * array2 xato bu usulda ko'paytirish

Matritsani songa ko'paytirish

In [27]:
np.dot(array1, array2)

array1.dot(array2)

#array1 * array2 - usulida ishlash xato

ValueError: shapes (3,2) and (5,) not aligned: 2 (dim 1) != 5 (dim 0)

Matritsani transponirlash

In [14]:
array1 = np.array([3, 4, 6, 8, 9, 2]).reshape(3, 2)

(array1.T).shape

array1.transpose()

array([[3, 6, 9],
       [4, 8, 2]])


Matritsa determinantini hisoblash

In [20]:
array = np.array([3, 4, 6, 8, 9, 2, -1, 0, 0]).reshape(3, 3)

linalg.det(array)

45.999999999999986

Matritsani (butun) darajaga ko'tarish

In [ ]:
linalg.matrix_power(array, 5)

Matritsaga teskari matritsani (inversiyasini) topish

In [ ]:
linalg.inv(array)

Matritsaga qarama-qarshi matritsani topish

In [26]:
array * -1

array([[-3, -4, -6],
       [-8, -9, -2],
       [ 1,  0,  0]])

# **Statistik amallar bajarish**

`sum` - Massiv elementlarining yig'indisi

In [28]:
array.sum()

31

`mean` - Massiv elementlarining modasi

In [29]:
array.mean()

3.4444444444444446

`cumsum` - Berilgan o'q bo'ylab elementlarning yig'indisi.

In [34]:
array.cumsum(axis=0)

array([[ 3,  4,  6],
       [11, 13,  8],
       [10, 13,  8]])