# **NumPydagi qo'shimcha funksiyalar: Bitiruv oqshomi. Phew**

In [18]:
import numpy as np

`concatenate()` - massivlarni birlashtirish

In [21]:
x = np.arange(0, 9)
y = np.arange(10, 15, 2)

z = np.concatenate([x, y])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10, 12, 14])

`stack()` - massivlarni o'q bo'yicha birlashitirish, vstack, hstack, dstack()

In [25]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

np.stack([x, y], axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

`array_split(n)` - massivni n ta massivga bo'lish

In [ ]:
a = np.array([3, 4, 5, 6, 4])

np.array_split(a, 7)

`where()` - massivdan kerakli elementlarning indekslarini qaytaradi

In [105]:
a = np.array([3, 4, 5, 6, 4, 12, 3])

x = np.where(a % 3 == 0)

type(x)

tuple

`searchsorted()` - massiv tartiblangan qidirilayotgan elementning indeksini qaytaradi

In [34]:
a = np.array([3, 17, 5, 6, 4, 12, 3]) #3 3 4 5 6 12 17

a.searchsorted(6)

1

`sort()` - massivni saralash

`unique()` - massiv elementlarini takrorlamagan holda qaytaradi

In [ ]:
a = np.array([3, 4, 3, 4, 0, -1, 0])

frozenset(np.unique(a))

`count_nonzero()` - massivning qiymati nolga teng bo'lmagan elementlari soni

In [ ]:
a = np.array([3, 4, 3, 4, 0, -1, 0])

np.count_nonzero(a)

`argmax()` - massivdagi eng katta elementning indeksini qaytaradi

In [42]:
a = np.array([3, 4, 3, 4, 0, -1, 0])

a.argmax()

a.max()

4

`argmin()` - massivdagi eng kichik elementning indeksini qaytaradi

In [43]:
a.argmin()

a.min()

-1

`repeat(n)` - massiv elementlarining har biri n martadan takrorlangan yangi massiv qaytaradi

In [58]:
array1 = a.repeat(3)

`full((m, n), value)` - massivni berilgan qiymat(lar) bilan berilgan o'lchamda to'ldirish

In [59]:
array2 = np.full((3, 3), 0)

# **Fayllar bilan ishlash**

`save()` - massivni fayl shaklida saqlash

In [53]:
np.save('ahmoqona_massiv', a)

`load()` - massiv(lar) saqlangan mavjud faylni yuklash

In [55]:
array = np.load('ahmoqona_massiv.npy')

array

array([ 3,  3,  3,  4,  4,  4,  3,  3,  3,  4,  4,  4,  0,  0,  0, -1, -1,
       -1,  0,  0,  0])

`savez()` - bir nechta massivni bitta faylga saqlash

In [60]:
np.savez('ikkita_ahmoqona_massiv', a=array1, b=array2) #kalit berib saqlanadi massivlar

In [63]:
arrays = np.load('ikkita_ahmoqona_massiv.npz')

arrays['a'] #kalitlar orqali o'qib olinadi

arrays['b']

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

`savez_compressed()` - massivlarni siqilgan holatda faylga saqlash

In [65]:
np.savez_compressed('siqilgan_ahmoqona_massivlar', a=array1, b=array2)

In [67]:
arrays = np.load('siqilgan_ahmoqona_massivlar.npz')

arrays['b']

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

a [7, 8, 9, 1, 2, 1, 3] =

6 ga qoldiqsiz bo'linadigan elementlarining o'rniga 1 dan boshlab sonlar bilan almashtirish kerak:



In [104]:
a = list(map(int, input().split()))
arr = np.array(a)

value = 1

for index, i in enumerate(arr):
     if i % 6 == 0:
        arr[index] = value
        value += 1

print(arr)

[1 2 3 3 4 4]
