# **Random funksiyalar**

In [1]:
from numpy import random
import numpy as np

# **NumPy massivini yaratish**

`random.rand(m, n)` - mxn o'lchamdagi 0 va 1 oralig'idagi haqiqiy sonlardan tashkil topgan massiv yaratadi (0, 1)

In [5]:
random.rand(3, 2)

array([[0.31338852, 0.82288749],
       [0.3306483 , 0.62130897],
       [0.26028519, 0.76089964]])

`random.randint(low, high=None, size=None, dtype=int)` - qiymatlari [low, high) oraliqda bo'lgan berilgan o'lchamdagi massiv yaratadi

In [ ]:
random.randint(low=3, high=8, size=(4, 3))

`random.choice(a, p=None)` - yozib tushuntirish biroz murakkab

In [16]:
x = random.choice([0, 3, 7, 9, 8, -1], p=[0.1, 0.1, 0.2, 0.2, 0.3, 0.1], size=(3, 2))

x

array([[8, 3],
       [8, 9],
       [9, 8]])

`random.shuffle()` - massiv elementlarini random tarzida almashtirib tashlaydi

In [17]:
x = np.arange(20)

random.shuffle(x)

x

array([14, 18,  4,  1, 17,  8, 16, 12, 10, 13, 11, 15,  9,  2,  5,  0, 19,
        3,  6,  7])